#!/bin/bash
# 
# Copyright (c) 2019 Marc Young
#
# encode for playback on Roku or Chromcast
# 
# shellcheck disable=SC1091
# shellcheck disable=SC2154

set -e

# shellcheck source=includes/helpers
source includes/helpers  
source includes/yaml.sh 

create_variables properties.yml

makedir "$HOME/$destination"

echo "Starting the $title"

echo "$episode" > episode

echo "$season" > season

for d in *; do
 cd "$d" || exit
 rip 
 echo "What is the name of the show?"
 read -r show_name
done

rm episode

echo "................."

echo "Script is complete."

exit
