#!/bin/bash

#Create directory structure
# shellcheck disable=SC1091


source includes/helpers

if ! command -v dvdbackup; then
   echo "please install dvdbackup"
   sleep 3
fi

[ -z "$1" ] && echo "Please add name of movie." && exit 1

[ -z "$2" ] && echo "Please add the number of discs." && exit 1

cd ~/Videos || exit 1

mkdir -p "$1"

cd "$1" || exit

for ((i=1; i<=$2; i++))
do
    vob
    read -r -p "Redo? [y/N] " response
    case "$response" in
        [yY][eE][sS]|[yY]) 
            echo "redoing"
            vob
            ;;
        *)
            echo "Please remove disc and insert another."
            echo "You may need to rename the folder."
            ls "$1"
            read -n 1 -s -r -p "Press any key to continue"
            sleep 16
            continue
            ;;
    esac
done