#!/usr/bin/env bash
#
#A file full of helper functions.
# shellcheck disable=SC1091
# shellcheck disable=SC2154

vob (){
    dvdbackup -i /dev/dvd -o . -Mp && eject
    echo "DVD is complete."
    echo "--------------------------------------"

}

rip () {
   source yaml.sh
   create_variables properties.yml

   echo "Loads from dvd"
 	SOURCE=/dev/cdrom

	lsdvd "${SOURCE}" || iso
	echo "${SOURCE}"
	lsdvd "${SOURCE}" > dvdinfo
	sed -i '/Disc Title:/d' dvdinfo
	sed -i '/Longest track:/d' dvdinfo

	sequence=$(wc -l < dvdinfo)

	for i in `seq $sequence`; do
	line=$(awk 'NR=='"$i" dvdinfo)
        	if echo "${line}" | grep -Eq 'Length: 00:0'
                	then
                	echo "Crap"
        	else
                	echo "great"
                	title=$(echo "${line}" | awk '{print $2}' | sed 's/^0*//' | tr -dc '[:alnum:]\n\r')
                	HandBrakeCLI -E copy:aac --input "${SOURCE}" --title "${title}" --output "${show_name}${S}${season}${E}${episode}".mp4 -e x264 -q "${quality}" -B 320;
                episode=$((episode+1))

        	fi

	done
}

makedir () {
   if [ -d "$1" ] 
   then
    new_dir="${1/\/-/}"
    mkdir "$new_dir"
    else
    mkdir "$1"
    fi
   exit
}